from collections.abc import Iterable
from typing import Any


class Category:
    @classmethod
    def join(cls, categories: Iterable["Category"]) -> "Category": ...

    @classmethod
    def meet(cls, categories: Iterable["Category"]) -> "Category": ...

    def super_categories(self) -> list["Category"]: ...
    def is_subcategory(self, other: "Category") -> bool: ...
    def Hom(self, codomain: Any) -> Any: ...
    def HomCategory(self) -> Any: ...
    def EndCategory(self) -> Any: ...
    def AutCategory(self) -> Any: ...
    def _make_named_class(
        self,
        name: Any,
        method_provider: Any,
        cache: bool = ...,
        picklable: bool = ...,
    ) -> type: ...
    def _repr_object_names(self) -> str: ...
    def __contains__(self, candidate: Any) -> bool: ...

