from collections.abc import Iterable, Sequence
from typing import Any


class Category:
    parent_class: type
    Constructors: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    @classmethod
    def join(cls, categories: Iterable["Category"]) -> "Category": ...

    @classmethod
    def meet(cls, categories: Iterable["Category"]) -> "Category": ...

    @classmethod
    def __classcall__(cls, *args: Any, **kwargs: Any) -> Any: ...

    @classmethod
    def _set_classcall(cls, value: Any) -> None: ...

    def super_categories(self) -> Sequence["Category"]: ...
    def extra_super_categories(self) -> Sequence["Category"]: ...
    def is_subcategory(self, other: "Category") -> bool: ...
    def Hom(self, codomain: Any) -> Any: ...
    def HomCategory(self) -> Any: ...
    def EndCategory(self) -> Any: ...
    def AutCategory(self) -> Any: ...
    def base_category(self: Any) -> "Category": ...
    def _with_axiom(self: Any, axiom: str) -> Any: ...
    def _make_named_class(
        self,
        name: Any,
        method_provider: Any,
        cache: bool = ...,
        picklable: bool = ...,
    ) -> type: ...
    def _repr_object_names(self) -> str: ...
    def __contains__(self, candidate: Any) -> bool: ...


class CategoryWithParameters(Category): ...


class JoinCategory(Category): ...
