from collections.abc import Iterator
from typing import Any

from sage.categories.category import Category


class EnumeratedSets(Category):
    class ParentMethods:
        def __iter__(self) -> Iterator[Any]: ...
        def __getitem__(self, index: Any) -> Any: ...
        def rank(self, element: Any) -> Any: ...
        def is_empty(self) -> bool: ...
        def is_countable(self) -> bool: ...
        def random_element(self) -> Any: ...
        def map(
            self,
            function: Any,
            name: str | None = ...,
            *,
            is_injective: bool = ...,
        ) -> Any: ...
