from typing import Any

from sage.categories.category import Category


class FacadeSets(Category):
    class ParentMethods:
        def is_facade(self) -> bool: ...
        def _element_constructor_(self, element: Any) -> Any: ...
        def facade_for(self) -> tuple[Any, ...] | bool: ...
        def is_parent_of(self, element: Any) -> bool: ...
        def __contains__(self, element: Any) -> bool: ...
        def _an_element_(self) -> Any: ...
