from collections.abc import Iterable
from typing import Any

from sage.categories.category import Category


class Posets(Category):
    class ParentMethods:
        def le(self, x: Any, y: Any) -> bool: ...
        def lt(self, x: Any, y: Any) -> bool: ...
        def ge(self, x: Any, y: Any) -> bool: ...
        def gt(self, x: Any, y: Any) -> bool: ...
        def upper_covers(self, x: Any) -> list[Any]: ...
        def lower_covers(self, x: Any) -> list[Any]: ...
        def order_ideal(self, elements: Iterable[Any]) -> Any: ...
        def order_filter(self, elements: Iterable[Any]) -> Any: ...
        def directed_subset(self, elements: Iterable[Any], direction: str) -> Any: ...
        def principal_order_ideal(self, x: Any) -> Any: ...
        def principal_order_filter(self, x: Any) -> Any: ...
        def subposet(self, elements: Iterable[Any]) -> Any: ...
        def order_ideal_toggle(self, ideal: Any, x: Any) -> Any: ...
        def order_ideal_toggles(
            self,
            ideal: Any,
            elements: Iterable[Any],
        ) -> Any: ...
        def is_order_ideal(self, subset: Iterable[Any]) -> bool: ...
        def is_order_filter(self, subset: Iterable[Any]) -> bool: ...
        def is_chain_of_poset(
            self,
            subset: Iterable[Any],
            ordered: bool = ...,
        ) -> bool: ...
        def is_antichain_of_poset(self, subset: Iterable[Any]) -> bool: ...
