from typing import Any

from sage.categories.category import Category
from sage.categories.facade_sets import FacadeSets


class EmptySetError(Exception): ...


class Sets(Category):
    def Facade(self) -> FacadeSets: ...

    class ParentMethods:
        def cardinality(self) -> Any: ...
        def is_empty(self) -> bool: ...
        def is_finite(self) -> bool: ...
        def __contains__(self, element: Any) -> bool: ...
        def _element_constructor_(self, element: Any) -> Any: ...
        def _an_element_(self) -> Any: ...
        def random_element(self) -> Any: ...
        def some_elements(self) -> list[Any]: ...
        def _sympy_(self) -> Any: ...
        def construction(self) -> Any: ...
        def _coerce_map_from_(self, source: Any) -> Any: ...

    class ElementMethods: ...

    class CartesianProducts(Category):
        class ParentMethods:
            def cardinality(self) -> Any: ...
            def is_finite(self) -> bool: ...
            def _element_constructor_(self, element: Any) -> Any: ...
            def __contains__(self, element: Any) -> bool: ...
            def construction(self) -> Any: ...
            def _coerce_map_from_(self, source: Any) -> Any: ...
            def _sympy_(self) -> Any: ...
