"""Production lifecycle test: exact documented config via subprocess shellout.

This test proves the plugin works as documented in README.md — using
sage -python -m mypy with a config file that contains exactly what the
README prescribes, including mypy_path = cache_dir/stubs.

Under mypy 2.0 (compiled via mypyc), search paths are frozen before
plugin loading, so mypy_path must be declared in the config file upfront.
This test exercises that exact constraint: no Python-API injection of
stub_root, no mypy_path_entries parameter — pure subprocess shellout from
the config file on disk.

Behavioral conjunction verified:
  plugin on  + valid code   → exit 0, no errors
  plugin on  + invalid code → exit nonzero, standard mypy error
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
REAL_CATEGORIES_ROOT = REPO_ROOT / "tests" / "real_categories"
FINITE_SMALL_GROUPS_VALID = REAL_CATEGORIES_ROOT / "finite_small_groups_valid.py"
FINITE_SMALL_GROUPS_INVALID = REAL_CATEGORIES_ROOT / "finite_small_groups_invalid.py"


def _sage_python_executable() -> str:
    """Return the sage -python interpreter path.

    The production invocation is ``sage -python -m mypy ...``.  For subprocess
    we resolve the Python interpreter that sage -python uses so we can invoke
    mypy directly without spawning an extra sage shell.
    """
    result = subprocess.run(
        ["sage", "-python", "-c", "import sys; print(sys.executable)"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _run_sage_mypy(
    config_path: Path,
    target_file: Path,
    *,
    cwd: Path,
) -> subprocess.CompletedProcess[str]:
    """Shell out to ``sage -python -m mypy`` exactly as the README prescribes."""
    return subprocess.run(
        [
            "sage",
            "-python",
            "-m",
            "mypy",
            "--config-file",
            str(config_path),
            "--no-incremental",
            str(target_file),
        ],
        capture_output=True,
        text=True,
        cwd=str(cwd),
    )


def test_production_lifecycle_valid_code_exits_clean(tmp_path: Path) -> None:
    """Plugin-on + valid code → exit 0 with no errors via subprocess shellout.

    Uses the exact config shape documented in README.md:
      [mypy]
      plugins = sage_mypy_category_plugin.plugin
      mypy_path = <cache_dir>/stubs        ← documented requirement

      [sage-mypy-category-plugin]
      packages = tests.real_categories
      roles = parent
      cache_dir = <cache_dir>

    No Python-API stub_root injection.  The mypy_path line is the only
    mechanism by which the generated stubs become visible.
    """
    cache_dir = tmp_path / "sage-category-cache"
    config_path = tmp_path / "mypy.ini"
    config_path.write_text(
        "\n".join(
            [
                "[mypy]",
                "plugins = sage_mypy_category_plugin.plugin",
                f"mypy_path = {cache_dir / 'stubs'}",
                "ignore_missing_imports = True",
                "",
                "[sage-mypy-category-plugin]",
                "packages = tests.real_categories",
                "roles = parent",
                f"cache_dir = {cache_dir}",
                "",
            ]
        )
    )

    result = _run_sage_mypy(
        config_path,
        FINITE_SMALL_GROUPS_VALID,
        cwd=REPO_ROOT,
    )

    assert result.returncode == 0, (
        f"Expected exit 0 for valid code with plugin on.\n"
        f"stdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )
    assert "no base method was found" not in result.stdout, (
        "Plugin should project provider MRO so @override resolves correctly.\n"
        f"stdout:\n{result.stdout}"
    )
    # Manifest and stubs were generated by the plugin during this run
    assert (cache_dir / "projection-manifest.json").is_file(), (
        "Plugin should have generated projection-manifest.json in cache_dir"
    )
    assert (cache_dir / "stubs").is_dir(), (
        "Plugin should have generated stubs/ directory in cache_dir"
    )


def test_production_lifecycle_invalid_code_exits_nonzero(tmp_path: Path) -> None:
    """Plugin-on + invalid code → exit nonzero with standard mypy error via shellout.

    Same config as the valid-code test.  A @override on a non-existent method
    should still produce a standard mypy error even though the plugin is active.
    """
    cache_dir = tmp_path / "sage-category-cache"
    config_path = tmp_path / "mypy.ini"
    config_path.write_text(
        "\n".join(
            [
                "[mypy]",
                "plugins = sage_mypy_category_plugin.plugin",
                f"mypy_path = {cache_dir / 'stubs'}",
                "ignore_missing_imports = True",
                "",
                "[sage-mypy-category-plugin]",
                "packages = tests.real_categories",
                "roles = parent",
                f"cache_dir = {cache_dir}",
                "",
            ]
        )
    )

    result = _run_sage_mypy(
        config_path,
        FINITE_SMALL_GROUPS_INVALID,
        cwd=REPO_ROOT,
    )

    assert result.returncode != 0, (
        f"Expected nonzero exit for invalid code (@override on non-existent method).\n"
        f"stdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )
    assert "no base method was found" in result.stdout, (
        "Plugin-on + @override on nonexistent method should produce standard mypy error.\n"
        f"stdout:\n{result.stdout}"
    )
