from typing import Any

from .category_object import CategoryObject


class Parent(CategoryObject):
    def __init__(self: Any, category: Any = ...) -> None: ...
    def Hom(self: Any, codomain: Any) -> Any: ...
    def change_ring(self: Any, base_ring: Any) -> Any: ...
    def _refine_category_(self, category: Any) -> None: ...
    def _test_not_implemented_methods(self) -> None: ...
