from typing import Any

from sage.categories.category import Category

from .category_object import CategoryObject


class Parent(CategoryObject):
    def __init__(self: Any, category: Any = ...) -> None: ...
    def Hom(self: Any, codomain: Category) -> Any: ...
    def _refine_category_(self, category: Any) -> None: ...
    def _test_not_implemented_methods(self) -> None: ...
